### ISSUE TITLE
Deploy Netlify Storybook preview on pull request

### ISSUE THREAD

**Issue by JQrdan** [matthew-chirgwin/kafka-java-vertx-starter#26]
# Feature

## Description

It would be nice to show a preview of the storybook for the specific branch that in a pull request

**Comment by JQrdan** [comment]
https://www.learnstorybook.com/intro-to-storybook/react/en/deploy/

**Comment by JQrdan** [comment]
Steps to deploy:

Point Netlify to this repo and add these build settings:

![image](https://user-images.githubusercontent.com/25624685/84031386-7c5a5880-a98d-11ea-903a-3f6b184621ae.png)


Then make sure this script exists in `package.json`:

```
"build-storybook": "build-storybook -o .out"
```

**Comment by matthew-chirgwin** [comment]
Would you like to to add the build storybook command as well? Netlify has been setup otherwise

**Comment by matthew-chirgwin** [comment]
This is now working - closing
