### ISSUE TITLE
Implement Message Element component

### ISSUE THREAD

**Issue by matthew-chirgwin** [matthew-chirgwin/kafka-java-vertx-starter#55]
Implement a Message Element component, as per https://github.com/matthew-chirgwin/kafka-java-vertx-starter/blob/ui/ui/docs/Architecture.md.

This component in effect is a span with properties abstracting type styles. 

Known required properties:
- isFirst (enables additional styling to indicate first entry)
- isError
- usage (either producer or consumer - expoted as a constant). Different renderings of the message prop are shown based on this
- message - a shape containing offset, partition, value, timestamp
- onInteraction - function invoked on hover/tab etc

Behavioural note: the consumer varient shows all data listed, plus a size in bytes

Items to produce (in order):

1. Documentation (draft in this issue for discussion)
2. Tests
3. Storybook entry
4. Component code

**Comment by matthew-chirgwin** [comment]
Consumer visuals:
<img width="538" alt="Screenshot 2020-06-17 at 08 37 49" src="https://user-images.githubusercontent.com/43138971/84869436-efdb2480-b075-11ea-8a3c-597aaf465546.png">
Producer visuals:
<img width="232" alt="Screenshot 2020-06-17 at 08 37 27" src="https://user-images.githubusercontent.com/43138971/84869439-f073bb00-b075-11ea-8819-657c37773778.png">

**Comment by ajborley** [comment]
Draft README for this component. A couple of questions/comments:

- Do we know what the shape of the error details is? Has that been defined yet?
- Do we want a single handler for all interactions? Or would onClick/onHover/onSelect make it  simpler to handle the different events? I'm happy with just the `onInteraction` handler but thought it worth raising.

# Message

This component represents a Kafka message, either produced to the broker or
consumed from the broker. Produced and consumed messages are styled and
structured differently and both can be supplied with interaction functions.

## Properties

Assuming use of the `Message` component directly, the named properties which are
expected are as follows:

- `className` - optional - add any specific styling classes to this component.
This will be appended after the class which sets the type style, allowing
modification of the styling if needed.
- `usage` - required - the style and structure applied to this component depending
  on the type of message. Must be either:
  - `consumer` - for messages that are consumed from Kafka
  - `producer` - for messages that are produced to Kafka
- `isFirst` - optional - enables additional styling to indicate the first message.
- `isError` - optional - enables additional styling to indicate an error occurred.
- `message` - required - a shape containing either the message topic, partition, offset,
  value and timestamp or the error details shape if `isError` is true.
- `onInteraction` - optional - a function invoked on hover, tab, click, etc. The interaction event, `usage` value and `message` value are passed to the function in that order.

_Note_: All `usage` values are exported alongside the component for ease of use.

Any property which is not matched will be passed onto the parent element
rendered as a part of this component. Do also note if using one of the named
styled components, the `usage` property is provided for you.

## Example usage

Example usage of the `Message` component, passing both a `usage` and custom
`className` property. This would result in a consumed message being
rendered, as well as the styling defined in the `myclass` css class.

```
<Message usage={'consumer'} className={'myclass'} message={aConsumedMessage}/>
```

For ease, `ConsumerMessage` and `ProducerMessage` named/higher order components
are also exposed for use. These in effect abstract the `usage` property away.
For example:

```
<ProducerMessage isFirst={true} message={aProducedMessage} />
```

The full set of exposed components and constants are as follows:

- `Message` - main Message component
- `ProducerMessage` - Message component with producer styling/structure
- `ConsumerMessage` - Message component with consumer styling/structure
- `PRODUCER` - producer usage constant
- `CONSUMER` - consumer usage constant

**Comment by nictownsend** [comment]
Wonder if we should be explicit - have `message` and `error` if the shapes are going to be different - then we state `error` overrides `message` if set?

**Comment by matthew-chirgwin** [comment]
>     * Do we know what the shape of the error details is? Has that been defined yet?

Responses from the backend will look as follows:
```
{"status":"SUCCESS","index":14,"topic":"mock_topic","partition":0,"offset":13,"timestamp":1592578829809,"value":"Content!"}
{"status":"ERROR","index":15}
```
These will be in an array, that the parent of this component (Producer/Consumer) will own. I expect it will check the status, and that can inform the isError case

>     * Do we want a single handler for all interactions? Or would onClick/onHover/onSelect make it  simpler to handle the different events? I'm happy with just the `onInteraction` handler but thought it worth raising.

From the design, one for all cases currently. Not to say we could have the same handler hooked up to all the different events

LGTM otherwise!
