### ISSUE TITLE
Implement a Messages Group component

### ISSUE THREAD

**Issue by matthew-chirgwin** [matthew-chirgwin/kafka-java-vertx-starter#56]
Implement a Messages Group component, as per https://github.com/matthew-chirgwin/kafka-java-vertx-starter/blob/ui/ui/docs/Architecture.md.

This component in effect is a layout component. Depending on property, children are rendered either in a row, or a column. If no children are provided, and empty state should be rendered.

Known required properties:
- usage (either producer or consumer - expoted as a constant). Triggers rendering in either a row or column
- messages - array of messages to render

Items to produce (in order):

1. Documentation (draft in this issue for discussion)
2. Tests
3. Storybook entry
4. Component code

**Comment by matthew-chirgwin** [comment]
Consumer:
<img width="561" alt="Screenshot 2020-06-17 at 08 37 17" src="https://user-images.githubusercontent.com/43138971/84869568-1e58ff80-b076-11ea-82ab-b5ac2a95f52b.png">
Producer:
<img width="537" alt="Screenshot 2020-06-17 at 08 37 05" src="https://user-images.githubusercontent.com/43138971/84869570-1ef19600-b076-11ea-9db5-52d227d6fb87.png">

**Comment by ajborley** [comment]
Draft README for this group, plus a couple of questions/comments:

 - The idea here is that the list of message/error objects is passed to this component which are iterated through inside the component, creating the list of `ConsumerMessage` or `ProducerMessage` element components that are rendered in the list. Have I got that right? 
 - The alternative is to pass a list of pre-created `ConsumerMessage` or `ProducerMessage` elements to this component directly as children, although that doesn't feel very well encapsulated.


# Messages

This group displays a list of [ConsumerMessage or ProducerMessage](../../Elements/Message)
elements, or an empty state if there are no messages to display. It acts as a
layout component. Depending on the `usage` property, children are rendered either
in a row or a column.

## Properties

Assuming use of the `Messages` component directly, the named properties which are
expected are as follows:

- `className` - optional - add any specific styling classes to this component.
This will be appended after the class which sets the type style, allowing
modification of the styling if needed.
- `usage` - required - the style and structure applied to this group depending
  on the type of messages. Must be either:
  - `consumer` - for messages that are consumed from Kafka
  - `producer` - for messages that are produced to Kafka
- `messages` - optional - array of a messages, each of which is a shape
  containing the Kafka topic, partition, offset, value and timestamp or a shape
  containing the error details.

Any property which is not matched will be passed onto the parent element
rendered as a part of this component.

## Example usage

Example usage of the `Messages` component, passing the `usage` and `messages` properties, plus a custom `className` property.

```
<Messages usage={'consumer'} className={'myclass'} messages={consumedMessages} />
```

Note that the `Messages` component itself is not exposed. Instead, `ConsumerMessages`
and `ProducerMessages` named/higher order components are exposed for use. These
in effect abstract the `usage` property away.

For example:

```
<ProducerMessages messages={producedMessages} />
```

The full set of exposed components and constants are as follows:

- `ProducerMessages` - Message component with producer styling/structure
- `ConsumerMessages` - Message component with consumer styling/structure
- `PRODUCER` - producer usage constant
- `CONSUMER` - consumer usage constant

**Comment by matthew-chirgwin** [comment]
> * The idea here is that the list of message/error objects is passed to this component which are iterated through inside the component, creating the list of `ConsumerMessage` or `ProducerMessage` element components that are rendered in the list. Have I got that right?
> 
> * The alternative is to pass a list of pre-created `ConsumerMessage` or `ProducerMessage` elements to this component directly as children, although that doesn't feel very well encapsulated.

As with most things, there are lots of different ways of achieving the same goal. The component here really provides us with two things - layout styling, and an empty state. In theory that could be re used in other contexts, so one option I was originally imagining was something like this:

In the producer panel (for instance):
```
<Messages type={PRODUCER} hasMessages={messages.length > 0}>
  {messages.map(msg => <ProducerMessage isFirst etc etc/>)}
</Messages>
```

Where Messages is really (for our purposes here) a symantic name from a structure point of view. The content being layed out could then be anything.

There is an argument for genericness vs current need - and I am more than happy to go with what you have proposed. I think the only suggestion I would have is the constants used here and in `Message` should be the same values. As it happens, I have defined a file in one of my PRs for a similar case: https://github.com/matthew-chirgwin/kafka-java-vertx-starter/blob/d42e88ded04d56e475710a3c36e086746a2b17f6/ui/src/Utils/constants.utils.js
