### ISSUE TITLE
Implement a Consumer Panel component

### ISSUE THREAD

**Issue by matthew-chirgwin** [matthew-chirgwin/kafka-java-vertx-starter#58]
Implement a Consumer Panel component, as per https://github.com/matthew-chirgwin/kafka-java-vertx-starter/blob/ui/ui/docs/Architecture.md.

This component owns state and datafetching responsibilities for the consumer side of the App.

Expected behaviours/capabilities:
- integrate with config/context for values
  - topic name, consumer endpoint address, currently selected record (get and set)
- owns a kafka websocket hook to consume from the backend
- renders the state via child components

Items to produce (in order):

1. Documentation (draft in this issue for discussion)
2. Tests
3. Storybook entry
4. Component code

**Comment by matthew-chirgwin** [comment]
Proposed README/feature file:

# Consumer

The Consumer panel represents the backend consumer in the starter application.
It show the user a summary of current consumption state, as well as the latest
30 messages which were consumed. In also will the user to interact with the
backend by offering the ability to start and stop the backend consumer.

# Usage

The Consumer acts as a panel. As such, the properties expected are as follows:

- getConsumerWebsocket - required - a function which returns a Websocket object
which is configured to connect to the backend consumer
- maxNumberOfMessages - the max number of messages to render. Defaults to 30.

# Behaviours

The behaviours and capabilities of this component are captured in it's 
[feature file](./Consumer.feature).

Feature file:
```
Feature: Consumer

Scenario: As a user, I can start and stop consumption as I choose
    Given i have a Consumer panel
    Then the consumer is not running
    When i start the consumer
    Then the consumer is running

Scenario: As a user, I can see statistics of what has been consumed so far
    Given i have a Consumer panel
    When i start the consumer
    Then it should display statistics about what has been consumed

Scenario: As a user, I can see what has been consumed so far
    Given i have a Consumer panel
    When i start the consumer
    Then i should be able to see the last "30" messages that have been consumed
```

**Comment by nictownsend** [comment]
> Scenario: As a user, I can start and stop consumption as I choose
    Given i have a Consumer panel
    Then the consumer is not running
    When i start the consumer
    Then the consumer is running
    When i stop the consumer
    Then the consumer is not running

Typically you it goes "given, when, then" without backtracking - and you use "and" for another step in the same phase.

But, I think there's an argument for bouncing between when/then if the steps are needed prior. (It almost needs a "then, when I")
