### ISSUE TITLE
Implement Producer Panel component

### ISSUE THREAD

**Issue by matthew-chirgwin** [matthew-chirgwin/kafka-java-vertx-starter#59]
Implement a Producer Panel component, as per https://github.com/matthew-chirgwin/kafka-java-vertx-starter/blob/ui/ui/docs/Architecture.md.

This component owns state and datafetching responsibilities for the producer side of the App.

Expected behaviours/capabilities:
- integrate with config/context for values
  - topic name, producer endpoint address, currently selected record (get and set)
- owns a kafka websocket hook to produce to the backend w/ ability to set custom payload
- renders the state via child components

Items to produce (in order):

1. Documentation (draft in this issue for discussion)
2. Tests
3. Storybook entry
4. Component code

**Comment by ajborley** [comment]
Draft README:

# Producer

The Producer panel represents the backend producer in the starter application.
It show the user a summary of current production state, as well as the latest
10 messages which were produced. It also allows user to interact with the
backend by offering the ability to start and stop the backend producer.

# Usage

The Producer acts as a panel. As such, the properties expected are as follows:

- getProducerWebsocket - required - a function which returns a Websocket object
which is configured to connect to the backend producer.
- topic - required - the name of the topic being produced from.
- maxNumberOfMessages - the max number of messages to render. Defaults to 10.

# Behaviours

The behaviours and capabilities of this component are captured in it's
[feature file](./Producer.feature).

Feature file:
```
Feature: Starter app Producer

Scenario: As a user, I can start and stop production as I choose
    Given I have a Producer panel
    When I start the producer
    Then the producer is running
    When I stop the producer
    Then the producer is not running

Scenario: As a user, I can provide the message value for produced messages
    Given I have a Producer panel
    And I set the message value to "A new value"
    When I start the producer
    And responses are returned
    Then the responses contain "A new value" as the message value 

Scenario: As a user, I can see statistics of what has been produced so far
    Given I have a Producer panel
    When I start the producer
    And responses are returned
    Then it should display statistics about what has been produced

Scenario: As a user, I am shown error states if production fails
    Given I have a Producer panel
    When I start the producer
    And Error responses are returned
    Then I should be shown error messages for those production failures

Scenario: As a user, I can see what has been produced so far
    Given I have a Producer panel
    And I have produced "30" messages already
    When I start the producer
    And responses are returned
    Then I should be able to see the last "30" messages that have been produced
```
