### ISSUE TITLE
Update App to contain expected content

### ISSUE THREAD

**Issue by matthew-chirgwin** [matthew-chirgwin/kafka-java-vertx-starter#60]
Update/prep the existing App component to have the content as per https://github.com/matthew-chirgwin/kafka-java-vertx-starter/blob/ui/ui/docs/Architecture.md.

Items to produce (in order):

1. Documentation and user story tests (draft in this issue for discussion)
2. Tests
3. Storybook entry
4. Component code updates

**Comment by nictownsend** [comment]
# App

This component acts as the container/composer of the application. It will render introductory text, and optionally a producer & consumer panel.

## Properties

- `className` - optional - add any specific styling classes to this component.
This will be appended to the root of the component.
- 'producer' - optional - boolean - enable producer
- 'consumer' - optional - boolean - enable consumer

## Usage

The full set of exposed components are as follows:
 - `App`

**Comment by nictownsend** [comment]
# User/e2e stories

Scenario: I can start producing
  Given I am on the homepage
  When I start the producer
  Then I see a new message appear in the producer status

Scenario: I can start consuming
  Given I am on the homepage
  When I start the consumer
  Then I see a new message appear in the consumer status

**Comment by matthew-chirgwin** [comment]
> # User/e2e stories
> 
> Scenario: I can start producing
> Given I am on the homepage
> When I start the producer
> Then I see a new message appear in the producer status
> 
> Scenario: I can start consuming
> Given I am on the homepage
> When I start the consumer
> Then I see a new message appear in the consumer status

LGTM - would also be worth adding a scenario that covers the on hover of a produced message, the equivelent consumed message is highlighted (and vice versa)

**Comment by nictownsend** [comment]
> > # User/e2e stories
> > Scenario: I can start producing
> > Given I am on the homepage
> > When I start the producer
> > Then I see a new message appear in the producer status
> > Scenario: I can start consuming
> > Given I am on the homepage
> > When I start the consumer
> > Then I see a new message appear in the consumer status
> 
> LGTM - would also be worth adding a scenario that covers the on hover of a produced message, the equivelent consumed message is highlighted (and vice versa)

Good call, updating the original post now

**Comment by matthew-chirgwin** [comment]
This issue will also need to cover integrating context where required:
- topic name
- the currently selected/highlighted message
